// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFIo2xCMFpaMpdqYMpGGUK5_siqs1ihk',
    appId: '1:628938806890:web:0e7250231401d4a68e5c13',
    messagingSenderId: '628938806890',
    projectId: 'flutterfire-ui-codelab-c0733',
    authDomain: 'flutterfire-ui-codelab-c0733.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-c0733.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb28NMjGcZquDZ4EOIYIMco03m1t_ama4',
    appId: '1:628938806890:android:3e132ce17ce6a4a38e5c13',
    messagingSenderId: '628938806890',
    projectId: 'flutterfire-ui-codelab-c0733',
    storageBucket: 'flutterfire-ui-codelab-c0733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9nhApBR6dh7YimMbouJMP0ysLw5SmDU',
    appId: '1:628938806890:ios:33d9f4728266ec668e5c13',
    messagingSenderId: '628938806890',
    projectId: 'flutterfire-ui-codelab-c0733',
    storageBucket: 'flutterfire-ui-codelab-c0733.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9nhApBR6dh7YimMbouJMP0ysLw5SmDU',
    appId: '1:628938806890:ios:33d9f4728266ec668e5c13',
    messagingSenderId: '628938806890',
    projectId: 'flutterfire-ui-codelab-c0733',
    storageBucket: 'flutterfire-ui-codelab-c0733.appspot.com',
    iosBundleId: 'com.example.complete',
  );

}